uses:
  - django
  - celery

pylint:
  disable:
    - django-not-configured
    - import-outside-toplevel
    - unused-import

pyflakes:
  disable:
    - F401

ignore-path:
  - venv

ignore-patterns:
  - .*migrations