version: "3"

services:
  app:
    command: >
      sh -c "python manage.py migrate &&
              python manage.py createsuperuser --noinput &&
              python manage.py runserver 0.0.0.0:8000"
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/app
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DATABASE_NAME
    ports:
      - "54321:54321"
  redis:
    image: redis:alpine
  celery:
    restart: always
    build:
      context: .
    command: >
        sh -c "celery -A shop_project worker -l info"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - app
volumes:
  postgres_data: